### PR TITLE
internal/models: Refactor user models

### LINKED ISSUE #17: Split usermeta out
User metadata is split out and there is a user profile page that allows the user to update profile information.

### LINKED ISSUE #28: UserProfile with []Student
User profiles need to be split out so that students are handled by a particular account, and then these students join a team.

### PR DESCRIPTION
**Pull request by the-maldridge**
This includes the things we talked about in the 4/4 meeting.

Resolves #17 
Resolves #28

### CODE REVIEW

**Comment by m-wynn** [comment]
From a technical perspective, User needs a UserProfile and []Students.  It also breaks mail.

**Comment by the-maldridge** [comment]
Mail has been broken for some time, so I'm not worried about that.  Once the models are approved additional work will be done on this branch to shim the types into other parts of the system.  Does the User need the profile and students embedded or is it sufficient to provide APIs that can manipulate these fields?

**Comment by m-wynn** [comment]
I'm more concerned about failure to compile.  Otherwise, APIs would be fine

**Comment by the-maldridge** [comment]
this was resolved somewhere in the merge of uber-branch monday.

**Pull request closed without merging**
